spring:
  main:
    banner-mode: off
  application:
    name: fpes-back
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8081/
  cloud:
    config:
      name: fpes-config-service
      label: master
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/fpes
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework.web: DEBUG
    org:
    hibernate:
      SQL: DEBUG
    type:
      descriptor:
        sql:
          BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: '*'
